### ISSUE TITLE
NullReferenceExceptions in certain template literals

### ISSUE THREAD

**Issue by GilianJuice** [trullock/NUglify#139]
If I try to minify the following code, I always get an exception:
```javascript
const testString = {
    js: {
        createClass(className = "MyClass", withInitiator = true) {
            let output = `
class ${className} {
test() {
`;
            output += `} async init(){ console.log("Class loaded..");     } } `;
        }
    }
};
```

This will cause the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUglify.JavaScript.JSParser.ParseArrowFunction(AstNode parameters)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
   at NUglify.Uglify.Js(String source, CodeSettings codeSettings)
```

This can be worked around by either adding a space before the backtick on line 7, or by deleteting the newline, so that the backtick will be after the bracket on line 6.

**Comment by trullock** [comment]
Fixed in 1.9.2

**Comment by GilianJuice** [comment]
I have tested this with version 1.9.2, but I'm still getting an error when I try to minify the code that I posted here.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUglify.JavaScript.JSParser.ParseArrowFunction(AstNode parameters)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
   at NUglify.Uglify.Js(String source, CodeSettings codeSettings)
```

**Comment by trullock** [comment]
Is this true, or was it really the new issue youve opened?

**Comment by GilianJuice** [comment]
No, this is true. I have tested the issues you fixed first, one of them worked, this one didn't. After that I started testing the rest of our javascript library with NUglify and that resulted in my other issue. I had to add a workaround for this issue before I was able to get the issue of https://github.com/trullock/NUglify/issues/142. After some searching I found the code that caused the error, which I posted in the other issue. These problems have nothing to do with each other.

**Comment by trullock** [comment]
OK, because theres a test for this in the solution with your exact code as the demo, see here: 

https://github.com/trullock/NUglify/blob/master/src/NUglify.Tests/TestData/JS/Input/Bugs/Bug139.js

Is that the same as your code, or is there something subtly different that i cant spot?

**Comment by trullock** [comment]
1.9.3 is just publishing with the fix to #142 in it, check that to see if its fixed, maybe i accidentally didnt publish the fix for this in 1.9.2. If so I'll fix the changelog, else can you provide exact repro steps to get the exception? thanks

**Comment by GilianJuice** [comment]
Hmm ok this is strange. If I create an empty console application and minify the same script, then I no longer get an error. We use NUglify in an application where users can save javascript to the database for a website. While saving, we minify that javascript with NUglify. It might be a problem with `\n` vs `\r\n` like you said.

**Comment by GilianJuice** [comment]
I have tested this and it seems to indeed be a problem with new lines; I have created an example project where you can reproduce the error here: https://github.com/GilianJuice/NUglify-test
In test.js, I have used only `\n` as newline, then you will get a NRE. If you change those newlines to `\r\n`, then it will work.

**Comment by trullock** [comment]
OK I can repro the issue using your code, I'll look into it...

**Comment by trullock** [comment]
OK got a fix for this, just ensuring all whitespace is properly handled

**Comment by GilianJuice** [comment]
Thank you for all your super fast fixes :).

**Comment by trullock** [comment]
Fixed in 1.9.4 (hopefully)

**Comment by GilianJuice** [comment]
Sorry for the late response, I have only just now had time to test this. It works perfectly now, thanks!
