### ISSUE TITLE
script type="application/ld+json" don't get minified properly

### ISSUE THREAD

**Issue by bertasoft** [trullock/NUglify#236]
Hey staff, It would be interesting if this library can minify the  ("<script type="application/ld+json"> some content </script>" ) schema org informations.

**Comment by trullock** [comment]
In what use case?

We added support for this content type a while ago, what are you trying to do that doesn't work?

**Comment by bertasoft** [comment]
The content type is inside the source, take a look view-source:https://www.polibevande.it/ is there an option to minify inside the html?

**Comment by trullock** [comment]
Please show me the C# and minimum snippet of HTML you're trying to minify which demonstrates your issue

**Comment by bertasoft** [comment]
```
using System;
using NUglify.Css;
using NUglify.Html;
using NUglify.JavaScript;

namespace Uglify
{
    class Program
    {
        private static readonly HtmlSettings HtmlSettings = new HtmlSettings()
        {
            RemoveOptionalTags = false, 
            ShortBooleanAttribute = false, 
            RemoveInvalidClosingTags = false,
            RemoveComments = true,
            RemoveEmptyAttributes = false,
            RemoveScriptStyleTypeAttribute = false,
            MinifyCssAttributes = true,
            CssSettings = new CssSettings {CommentMode = CssComment.None, IgnoreAllErrors = true},
            JsSettings = new CodeSettings {PreserveImportantComments = false}
        };
        
        static void Main(string[] args)
        {
            var html = "<html>" + Environment.NewLine +
                       "<head>" + Environment.NewLine +
                       "<script type=\"text/javascript\">" + Environment.NewLine +
                       "var js = 'somevar'; " + Environment.NewLine +                       
                       "</script>" + Environment.NewLine +
                       "<script type=\"application/ld+json\">{" + Environment.NewLine +
                       "\"@context\": \"http://schema.org/\"," + Environment.NewLine +
                       "\"@type\": \"WebSite\"," + Environment.NewLine +
                       "\"url\": \"https://domain.ext\", " + Environment.NewLine +
                       "\"name\": \"Name Site\"," + Environment.NewLine +
                       "\"alternateName\": null" + Environment.NewLine +
                       "\"}</script>\"" + Environment.NewLine +
                       "</head>" + Environment.NewLine +
                       "<body>" + Environment.NewLine + 
                       "</body>"  + Environment.NewLine +
                       "</html>";

            var result = NUglify.Uglify.Html(html, HtmlSettings);
            
            html = result.Code;
            
            Console.Write(html);

            Console.ReadKey();
        }
    }
}
```


this is the output:

<html><head><script type=text/javascript>var js="somevar"</script><script type=application/ld+json>{

"@context": "http://schema.org/",
"@type": "WebSite",
"url": "https://domain.ext",
"name": "Name Site",
"alternateName": null
"}</script>"</head><body></body></html>


"<script type=application/ld+json>"  is not inlined

**Comment by bertasoft** [comment]
There are some issues with this editor that cut off some code. Look the attachment
![Output](https://user-images.githubusercontent.com/926243/109776419-d4fc1080-7c02-11eb-8f83-29863afb333e.png)

**Comment by trullock** [comment]
"cut off some code" - please specify what you think is missing

**Comment by trullock** [comment]
And what version of NUglify are you using?

**Comment by bertasoft** [comment]
> "cut off some code" - please specify what you think is missing

i'm talking about github editor. Nevermind look the attachment
![Output2](https://user-images.githubusercontent.com/926243/109778233-df1f0e80-7c04-11eb-9cd5-ea2da4c288b7.png)

**Comment by bertasoft** [comment]
> And what version of NUglify are you using?

1.13.3

**Comment by trullock** [comment]
OK, theres definitely a bug here. Curious.

On it!

**Comment by trullock** [comment]
so first off youve got a syntax error, your last line:

```"}</script>```

remove that leading `"`

this is probably just a bug in your code example here though.

Otherwise theres a fix coming for the real issue

**Comment by bertasoft** [comment]
> so first off youve got a syntax error, your last line:
> 
> `"}</script>`
> 
> remove that leading `"`
> 
> this is probably just a bug in your code example here though.
> 
> Otherwise theres a fix coming for the real issue

yes i saw but the error concerns only the example, anyway thanks.

**Comment by trullock** [comment]
Fixed in 1.13.4

**Comment by bertasoft** [comment]
Well, with this i've got same result, the bug is still presents. Try to minify this 

```
<html>
<head>
<script type=application/ld+json>{
    "@context": "http://schema.org",
    "@type": "Organization",
    "name": "Some Text",
    "logo": "https://domain.ext/android-icon-144x144.png",
    "url": "https://domain.ext",
    "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "+000000000",
        "contactType": "Sales",
        "email": "some@domain.ext,
        "contactOption": "",
        "areaServed": "Country",
        "availableLanguage": "Language"
    },
    "address": {
        "@type": "PostalAddress",
        "addressCountry": "Country",
        "addressLocality": "City",
        "addressRegion": "VR",
        "postalCode": "00000",
        "streetAddress": "Address, 3"
    }
}</script>
</head>
<body>

</body>
</html>
```

Vers.: 1.13.9

**Comment by trullock** [comment]
There is a passing test for `application/ld+json`, so you must be doing something different, can you show the code youre using and the outputted html it generates?

**Comment by trullock** [comment]
You have invalid json, youre missing a closing `"` here:

`"email": "some@domain.ext,`
