### ISSUE TITLE
.NET 6 ambiguity with System.Linq.Enumerable.DistinctBy

### ISSUE THREAD

**Issue by Stryxus** [trullock/NUglify#268]
With .NET 6 right around the corner, I started using it due to its improvements and LTS status. However, using it with FFMpegCore is not possible and changing the project to .NET 6 creates an ambiguity error between `System.Linq.Enumerable.DistinctBy` and `NUglify.Helpers.NUglifyExtensions.DistincyBy` in class https://github.com/trullock/NUglify/blob/master/src/NUglify/Css/CssColorName.cs

**Comment by trullock** [comment]
Do the two methods do the same thing?

If so add conditional compilation flags for `< .net 6`  around the nuglify helper

**Comment by trullock** [comment]
although why are you compiling NUglify yourself into .NET 6?

**Comment by trullock** [comment]
Sorry youre gonna have to rewind a bit, what's FFMpegCore relationship to NUglify/what youre doing?

**Comment by Stryxus** [comment]
Wops, sorry, corrected it, im working with both and a few other things so names are getting a little mixed up.

**Comment by trullock** [comment]
Can you create a minimal repro of your problem please and share it

**Comment by Stryxus** [comment]
I will, give me a few minutes.

**Comment by Stryxus** [comment]
I have made a repo for it. https://github.com/Stryxus/NUglify-NET5-NET6-Testing

**Comment by Stryxus** [comment]
Seems its more of a wide-spread issue. Interestingly enough when I remove all target frameworks and just target .NET 5, it works fine. 
![image](https://user-images.githubusercontent.com/11709044/128247472-5d0cc096-fba7-4caa-b6b2-dc4ef6e0cbff.png)

**Comment by trullock** [comment]
OK, I can take a look at this

However, why do you need to build this to target .NET 5 or 6? Do the existing binaries not work? If not, whats the problem?

**Comment by trullock** [comment]
Adding net50 to the current set of target frameworks works just fine under VS2019. I'll add this to the codebase, not sure what value it delivers but it wont hurt

**Comment by trullock** [comment]
And compiling to net60 under VS2022 latest preview also works (the Linq bug not withstanding)

I've pushed a `net60` branch which includes both fixes. I'll publish this when net60 is released.

Let me know if you need anything else

**Comment by Stryxus** [comment]
> And compiling to net60 under VS2022 latest preview also works (the Linq bug not withstanding)
> 
> I've pushed a `net60` branch which includes both fixes. I'll publish this when net60 is released.
> 
> Let me know if you need anything else

Thanks this is all I wanted. I personally am not a fan of having to edit submodules each time.

**Comment by EhtashamBukhari** [comment]
I'm still facing that issue while trying to upgrade to .NET 6.

**Comment by pawansingh168** [comment]
> I have made a repo for it. https://github.com/Stryxus/NUglify-NET5-NET6-Testing

Not available
